### ISSUE TITLE
Patch Bug After Upgrading to 6.0

### ISSUE THREAD

**Issue by NickEmpetvee** [PostgREST/postgrest#1396]
Hi guys. I discovered an issue after upgrading to 6.0 that wasn't happening with 5.2. I'm using Axios in React 16.8.0.

In 5.2 the below code works fine. It updates base_branch's region with a new ID where it matched an old ID. If no matches were found, it closes out without making any change.

```
await API.patch('/base_branch?region=eq.' + oldRegionID,
      newRegionData
    )
```
In 6.0 the same code yields this error if there isn't a match for REGION. However it works as expected if there is a match:

```
PATCH http://localhost:3001/base_branch?region=eq.118 404 (Not Found)
RegionContext.js:245 Error: Request failed with status code 404
    at createError (createError.js:17)
    at settle (settle.js:19)
    at XMLHttpRequest.handleLoad (xhr.js:60)
```
Any ideas on why the behavior is different when a match isn't found?

**Comment by steve-chavez** [comment]
Hmm. That's more of a bug fix than a bug.

The bug was reported on https://github.com/PostgREST/postgrest/issues/1257 and solved in https://github.com/PostgREST/postgrest/pull/1272.

Basically when PATCH didn't match any rows you'd get an incorrect `204`(your library interprets this as success and yields no error) but now we return a correct `404`(library yields error).

**Comment by NickEmpetvee** [comment]
Thanks for clearing it up @steve-chavez .
