### ISSUE TITLE
postgrest 0.5.0.0 fails to build on macOS Mojave

### ISSUE THREAD

**Issue by fxcoudert** [PostgREST/postgrest#1187]
### Environment

* PostgreSQL version: 10.5
* PostgREST version: 0.5.0.0
* Operating system: macOS 10.14
* ghc 8.2.2

### Description of issue

Compilation fails with:

```
Failed to install hasql-transaction-0.5.2
Build log ( /private/tmp/postgrest-20180930-18217-zso4f/postgrest-0.5.0.0/.cabal-sandbox/logs/ghc-8.2.2/hasql-transaction-0.5.2-3hgcJnuaYho6eF0f5aWguu.log ):
cabal: Entering directory '/private/tmp/cabal-tmp-18637/hasql-transaction-0.5.2'
Configuring hasql-transaction-0.5.2...
clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/usr/local/opt/ghc@8.2/lib' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/usr/local/opt/icu4c/lib' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/usr/local/opt/openssl/lib' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/usr/local/opt/readline/lib' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/usr/local/lib' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries' [-Wunused-command-line-argument]
Preprocessing library for hasql-transaction-0.5.2..
Building library for hasql-transaction-0.5.2..
[1 of 8] Compiling Hasql.Transaction.Private.Prelude ( library/Hasql/Transaction/Private/Prelude.hs, dist/dist-sandbox-da9fca80/build/Hasql/Transaction/Private/Prelude.o )
[2 of 8] Compiling Hasql.Transaction.Private.Model ( library/Hasql/Transaction/Private/Model.hs, dist/dist-sandbox-da9fca80/build/Hasql/Transaction/Private/Model.o )
[3 of 8] Compiling Hasql.Transaction.Private.SQL ( library/Hasql/Transaction/Private/SQL.hs, dist/dist-sandbox-da9fca80/build/Hasql/Transaction/Private/SQL.o )
[4 of 8] Compiling Hasql.Transaction.Private.Queries ( library/Hasql/Transaction/Private/Queries.hs, dist/dist-sandbox-da9fca80/build/Hasql/Transaction/Private/Queries.o )

library/Hasql/Transaction/Private/Queries.hs:6:1: error:
    Could not find module ‘Hasql.Query’
    Use -v to see a list of the files searched for.
  |
6 | import qualified Hasql.Query as A
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Leaving directory '/private/tmp/cabal-tmp-18637/hasql-transaction-0.5.2'
Completed    hasql-pool-0.5
Completed    lens-4.17
cabal: Error: some packages failed to install:
hasql-transaction-0.5.2-3hgcJnuaYho6eF0f5aWguu failed during the building
phase. The exception was:
ExitFailure 1
```

**Comment by steve-chavez** [comment]
That version had some issues when building it with cabal(we didn't pin some libs versions), I suggest trying  `v5.1.0`. Also, not sure if it'll build with ghc `8.2.2`(see https://github.com/PostgREST/postgrest/issues/1109), try `8.0.2`.

**Comment by fxcoudert** [comment]
5.1.0 doesn't build either, sadly: https://github.com/Homebrew/homebrew-core/pull/32582

**Comment by fxcoudert** [comment]
Homebrew does not ship ghc@8.0 anymore. If postgrest does not build with recent compiler versions (we currently carry 8.2 and 8.4), it will have to be removed from Homebrew core, sadly.

**Comment by begriffs** [comment]
FX Coudert wrote:
> Homebrew does not ship ghc@8.0 anymore.

That's surprising because 8.0.2 was from just *last year.* We aren't
talking about ancient history here.

> (we currently carry 8.2 and 8.4)

OK, so brew *is* able to support more than one GHC version. Is the
policy to arbitrarily support no more than two minor versions?

**Comment by fxcoudert** [comment]
https://docs.brew.sh/Versions
The policy is to support versions that are actively maintained by upstream (i.e. new versions are released in that branch, including security fixes). We try to be a repository of current software, not a historical library carrying all versions, as we do not have the will or manpower to do that.

**Comment by iMichka** [comment]
@fxcoudert `postgrest` was already in the list of packages that needed to be migrated to ghc 8.4, see #25568. That issue is from March 2018.

Considering this + the fact that it does not build on Mojave + the fact that ghc 8.6.x will hopefully be added soon + ghc 8.0 is probably not coming back in homebrew, and that we would like to drop ghc 8.2, I would propose to remove `postgrest` from homebrew-core until it gets fixed. Or drop support for Mojave here, but I am worried that we may need to keep ghc 8.2 around way longer than needed.

**Comment by robx** [comment]
postgrest is now back in homebrew at version 6.0.0: https://github.com/Homebrew/homebrew-core/blob/master/Formula/postgrest.rb

so this might be closed?
