### ISSUE TITLE
Support hspec-wai 0.10

### ISSUE THREAD

**Issue by felixonmars** [PostgREST/postgrest#1451]
### Environment

* PostgREST version: 6.0.2
* Operating system: Arch Linux x86_64

### Description of issue

Currently postgrest's test suite doesn't build with hspec-wai 0.10 series:

```
Building test suite 'spec' for postgrest-6.0.2..
[ 1 of 30] Compiling Feature.ConcurrentSpec ( test/Feature/ConcurrentSpec.hs, dist/build/spec/spec-tmp/Feature/ConcurrentSpec.dyn_o )

test/Feature/ConcurrentSpec.hs:43:30: error:
    • Expecting one more argument to ‘WaiSession’
      Expected kind ‘* -> *’, but ‘WaiSession’ has kind ‘* -> * -> *’
    • In the second argument of ‘MonadBaseControl’, namely ‘WaiSession’
      In the instance declaration for ‘MonadBaseControl IO WaiSession’
   |
43 | instance MonadBaseControl IO WaiSession where
   |                              ^^^^^^^^^^

test/Feature/ConcurrentSpec.hs:52:23: error:
    • Expecting one more argument to ‘WaiSession’
      Expected kind ‘* -> *’, but ‘WaiSession’ has kind ‘* -> * -> *’
    • In the second argument of ‘MonadBase’, namely ‘WaiSession’
      In the instance declaration for ‘MonadBase IO WaiSession’
   |
52 | instance MonadBase IO WaiSession where
   |                       ^^^^^^^^^^
```

It would be nice if the new version could be supported.

**Comment by steve-chavez** [comment]
@felixonmars Fixed in #1456.

**Comment by felixonmars** [comment]
Thanks!
